# Site settings
title:        Jihye Lee 이지혜
description:  Freelance Font-end Web Developer
baseurl:      ""
url:          https://designmeme.github.io
author:       Jihye Lee
email:        ghe.lee19@gmail.com
#logo:         "" # og_image
index:
  en: /
  ko: /ko/
feed:
  en: /feed.xml
  ko: /feed-ko.xml

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      type: pages
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      type: posts
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: ko
    values:
      lang: ko
  - scope:
      path: _posts/en
    values:
      lang: en
      categories: en blog
  - scope:
      path: _posts/ko
    values:
      lang: ko
      categories: ko blog

# Custom vars
google_adsense: ca-pub-5213448719952520
google_analytics: UA-93339811-1
github_username:  designmeme
copyright: © Jihye Lee
favicon_version: 0.1.0

# Build settings
permalink:        /:categories/:title/
timezone:         GMT
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - README.md
  - node_modules
  - vendor
#gems:
sass:
  sass_dir: assets/sass
#  style: compressed